import { Typography } from "@mui/material";
import { Navbar } from "components/Navbar/Navbar";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const AboutPage = () => {
  return (
    <div>
      <Head>
        <title>About</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={styles.container}>
        <div className={styles.mainContainer}>
          <Typography variant='h3'>This is about page</Typography>
          <Navbar />
        </div>
      </div>
    </div>
  );
};

export default AboutPage;
