import type { NextPage } from "next";
import { useState, useEffect } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Navbar } from "components/Navbar/Navbar";
import { useQuery } from "@apollo/client";
import { GET_ALL_POSTS } from "query/posts";
import { FeedPost } from "components/FeedPost/FeedPost";
import { Box } from "@mui/material";
import Skeleton from "components/Skeleton/Skeleton";
import type { Post } from "typings/post";

const Home: NextPage = () => {
  const [postsAndComments, setPostsAndComments] = useState<Post[]>([]);
  const { data, error, loading } = useQuery(GET_ALL_POSTS);
  const posts = postsAndComments.filter(
    //get description type by tag #comment#
    (post) => post.description.substring(0, 9) !== "#comment#"
  );

  useEffect(() => {
    if (data) {
      setPostsAndComments(data.feed.links);
    }
  }, [data, postsAndComments, postsAndComments]);

  if (loading) {
    return (
      <div className={styles.container}>
        <div className={styles.mainContainer}>
          <Box sx={{ minWidth: 430 }}>
            <Skeleton />
            <Skeleton />
          </Box>
          <Navbar />
        </div>
      </div>
    );
  }

  if (error) {
    return <h1>Error...</h1>;
  }

  return (
    <div className={styles.container}>
      <div className={styles.mainContainer}>
        <Head>
          <title>Home page</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <Box sx={{ minWidth: 430 }}>
          {posts.map((post) => {
            return (
              <FeedPost
                key={post.id}
                description={post.description}
                url={post.url}
                postedBy={post.postedBy}
                votes={post.votes}
                id={post.id}
              />
            );
          })}
        </Box>

        <Navbar />
      </div>

      <footer className={styles.footer}>Sagynzhan Kalel</footer>
    </div>
  );
};

export default Home;
